gazebo_ros_control:
  pid_gains:
    front_left_joint:
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    front_right_joint:
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    back_left_joint:
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    back_right_joint:
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  chassis_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: [ 'front_left_joint', 'back_left_joint' ]
    right_wheel: [ 'front_right_joint', 'back_right_joint' ]
    publish: 100
    pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.001 ]
    twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.001 ]
    enable_odom_tf: true
    cmd_vel_timeout: 0.25
    required_drive_mode: 3
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0
    base_frame_id: base_link
    wheel_separation: 0.674
    wheel_radius: 0.165
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        min_velocity: -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.2  # m/s^2
        min_acceleration: -1.2 # m/s^2
        has_jerk_limits: false
  #        max_jerk: 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5  # rad/s^2
        has_jerk_limits: false
#        max_jerk: 2.5  # rad/s^3
